title: Conference Deadlines # (Maintained by @SSIG. Original by @abshkdz)
description: Countdowns to CV/ML/Biometrics/Sensor/AI conference deadlines.
author: SSIG (Original by Abhishek Das)

domain: "ssig.github.io/"
baseurl: "/deadlines"

twitter_username: ssig_ufmg
twitter_hashtag: machinelearning
github_username: ssig
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2
